package com.example.examdemo.Controller;

import com.example.examdemo.Model.Student;
import com.example.examdemo.Repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@RestController
@CrossOrigin(value = "*")
public class StudentRestController
{
    @Autowired
    StudentRepository studentRepository;

    @GetMapping("/students")
    public List<Student> students(){
        List<Student> list = studentRepository.findAll();
        return list;
    }

    @PutMapping("/students")
    public List<Student> addStudent()
    {
        Student stud = new Student();
        stud.setDayOfBirth(LocalDate.now());
        stud.setTimeOfBirth(LocalDateTime.now());
        List<Student> list = studentRepository.findAll();
        stud.setName("Autogenerated size=" + list.size());
        studentRepository.save(stud);
        System.out.println("Student saved =" + stud.getName());
        return list;
    }

    @GetMapping("/")
    public String rootMehtod()
    {
            return "hello";
    }
}
